# Generated by Django 5.2.14 on 2026-05-10 03:49

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Clinic", "0002_delete_doctor"),
        ("Receptions", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="نام خانوادگی"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient", "کاربر"),
                            ("doctor", "پزشک"),
                            ("reception", "پذیرش"),
                            ("supervisor", "سوپروایزر"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("mobile_number", models.CharField(max_length=14)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "supervisors",
            },
        ),
        migrations.CreateModel(
            name="Reception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "privileges",
                    models.ManyToManyField(
                        blank=True,
                        related_name="receptions",
                        to="Clinic.clinics",
                        verbose_name="دسترسی کلینیک\u200cها",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "receptions",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "insurance_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="base_patients",
                        to="Receptions.insurances",
                    ),
                ),
                (
                    "insurance_full",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="full_patients",
                        to="Receptions.insurances",
                    ),
                ),
                (
                    "insurance_supp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supp_patients",
                        to="Receptions.insurances",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "patients",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speciality", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "super_speciality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Biography"),
                ),
                ("pt_cap", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "فعال"), ("inactive", "غیرفعال")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        default="docs/def.jpg",
                        error_messages={
                            "blank": "لطفاً یک عکس انتخاب کنید.",
                            "empty": "فایل بارگذاری شده خالی است.",
                            "invalid": "فایل انتخاب شده معتبر نیست.",
                            "invalid_image": "فایل ارسالی خراب می\u200cباشد",
                            "missing": "هیچ فایلی برای بارگذاری انتخاب نشده است.",
                        },
                        upload_to="docs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"],
                                message="فقط فایل\u200cهای تصویری با فرمت JPG, JPEG, PNG مجاز هستند.",
                            )
                        ],
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="Clinic.clinics",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="doctors",
                        to="Clinic.doctorservices",
                        verbose_name="خدمات",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "doctors",
            },
        ),
        migrations.CreateModel(
            name="SubUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        error_messages={
                            "blank": "این فیلد نمی\u200cتواند خالی باشد",
                            "max_length": "تعداد کاراکترها بیشتر از حد مجاز است",
                        },
                        max_length=30,
                        verbose_name="نام",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        error_messages={
                            "blank": "این فیلد نمی\u200cتواند خالی باشد",
                            "max_length": "تعداد کاراکترها بیشتر از حد مجاز است",
                        },
                        max_length=30,
                        verbose_name="نام خانوادگی",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        error_messages={
                            "blank": "این فیلد نمی\u200cتواند خالی باشد",
                            "max_length": "حداکثر کاراکتر مجاز 10 عدد می\u200cباشد",
                            "unique": "فردی با این کدملی در سیستم وجود دارد",
                        },
                        max_length=10,
                        unique=True,
                        verbose_name="کدملی",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("Siblings", "خواهر یا برادر"),
                            ("Spouse", "همسر"),
                            ("Children", "فرزندان"),
                        ],
                        max_length=30,
                        verbose_name="نسبت با کاربر",
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        error_messages={
                            "invalid": "فرمت تاریخ نامعتبر است. لطفاً تاریخ را به صورت سال-ماه-روز وارد کنید.",
                            "required": "تاریخ تولد الزامی است.",
                        },
                        verbose_name="تاریخ تولد",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_users",
                        to="Account.patient",
                        verbose_name="کاربر اصلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub User",
                "verbose_name_plural": "Sub Users",
                "db_table": "Sub_User",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(fields=["user"], name="Sub_User_user_id_657767_idx"),
                    models.Index(
                        fields=["national_id"], name="Sub_User_nationa_f03869_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["clinic"], name="doctors_clinic__3f79f6_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["status"], name="doctors_status_f1630d_idx"),
        ),
    ]
