# Generated by Django 5.2.14 on 2026-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("Male", "مرد"), ("Female", "زن")],
                default="Male",
                max_length=10,
            ),
        ),
    ]
