# Generated by Django 5.2.14 on 2026-05-10 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0002_user_sex"),
        ("Clinic", "0002_delete_doctor"),
        ("Receptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctors",
                to="Clinic.clinics",
                verbose_name="کلینیک محل فعالیت",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="pt_cap",
            field=models.PositiveIntegerField(
                default=10, verbose_name="ظرفیت بیمار در روز"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="speciality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="تخصص"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="status",
            field=models.CharField(
                choices=[("active", "فعال"), ("inactive", "غیرفعال")],
                default="active",
                max_length=10,
                verbose_name="وضعیت فعالیت",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="super_speciality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="فوق تخصص"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="base_patients",
                to="Receptions.insurances",
                verbose_name="بیمه پایه",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_full",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="full_patients",
                to="Receptions.insurances",
                verbose_name="بیمه فول درمان",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_supp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supp_patients",
                to="Receptions.insurances",
                verbose_name="بیمه تکمیلی",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(max_length=14, verbose_name="موبایل"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "کاربر"),
                    ("doctor", "پزشک"),
                    ("reception", "پذیرش"),
                    ("supervisor", "سوپروایزر"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="نقش",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("Male", "مرد"), ("Female", "زن")],
                default="Male",
                max_length=10,
                verbose_name="جنسیت",
            ),
        ),
    ]
