# Generated by Django 5.2.14 on 2026-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0003_alter_doctor_clinic_alter_doctor_pt_cap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
