# Generated by Django 5.2.14 on 2026-05-10 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0004_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
