# Generated by Django 5.2.14 on 2026-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0005_remove_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "کاربر"),
                    ("doctor", "پزشک"),
                    ("reception", "پذیرش"),
                    ("supervisor", "سوپروایزر"),
                ],
                db_index=True,
                default="patient",
                max_length=20,
                verbose_name="نقش",
            ),
        ),
    ]
