# Generated by Django 5.2.14 on 2026-05-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[("Active", "فعال"), ("Inactive", "غیرفعال")],
                default="Active",
                max_length=10,
                verbose_name="وضعیت فعالیت",
            ),
        ),
        migrations.AddField(
            model_name="reception",
            name="status",
            field=models.CharField(
                choices=[("Active", "فعال"), ("Inactive", "غیرفعال")],
                default="Active",
                max_length=10,
                verbose_name="وضعیت فعالیت",
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="status",
            field=models.CharField(
                choices=[("Active", "فعال"), ("Inactive", "غیرفعال")],
                default="Active",
                max_length=10,
                verbose_name="وضعیت فعالیت",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="status",
            field=models.CharField(
                choices=[("Active", "فعال"), ("Inactive", "غیرفعال")],
                default="Active",
                max_length=10,
                verbose_name="وضعیت فعالیت",
            ),
        ),
    ]
