# Generated by Django 5.2.14 on 2026-05-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0007_patient_status_reception_status_supervisor_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="پزشکان محبوب"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_top",
            field=models.BooleanField(default=False, verbose_name="پزشکان برتر"),
        ),
    ]
