# Generated by Django 5.2.14 on 2026-05-09 03:31

import uuid

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "type",
                    models.CharField(
                        choices=[("normal", "عادی"), ("paraclinic", "پاراکلینیک")],
                        default="normal",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clinic",
                "verbose_name_plural": "Clinics",
                "db_table": "Clinics",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(fields=["type"], name="Clinics_type_2041ab_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "type"), name="unique_clinic_name_type"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctorServices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام خدمت"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "Doctor_Service",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="Doctor_Serv_name_4f6a2b_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        error_messages={
                            "blank": "این فیلد نمی\u200cتواند خالی باشد",
                            "max_length": "تعداد کاراکترها بیشتر از حد مجاز است",
                        },
                        max_length=100,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        error_messages={
                            "blank": "این فیلد نمی\u200cتواند خالی باشد",
                            "max_length": "تعداد کاراکترها بیشتر از حد مجاز است",
                        },
                        max_length=100,
                    ),
                ),
                ("speciality", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "super_speciality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Biography"),
                ),
                (
                    "pt_cap",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="ظرفیت بیمار",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "مرد"), ("Female", "زن")],
                        default="Male",
                        error_messages={
                            "invalid_choice": "مقدار ارسالی معتبر نمی\u200cباشد"
                        },
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "فعال"), ("Deactive", "غیرفعال")],
                        default="Active",
                        error_messages={
                            "invalid_choice": "مقدار ارسالی معتبر نمی\u200cباشد"
                        },
                        max_length=10,
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        default="docs/def.jpg",
                        error_messages={
                            "blank": "لطفاً یک عکس انتخاب کنید.",
                            "empty": "فایل بارگذاری شده خالی است.",
                            "invalid": "فایل انتخاب شده معتبر نیست.",
                            "invalid_image": "فایل ارسالی خراب می\u200cباشد",
                            "missing": "هیچ فایلی برای بارگذاری انتخاب نشده است.",
                        },
                        upload_to="docs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"],
                                message="فقط فایل\u200cهای تصویری با فرمت JPG, JPEG, PNG مجاز هستند.",
                            )
                        ],
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        error_messages={
                            "invalid": "کلینیک ارسالی نامعتبر می\u200cباشد",
                            "invalid_pk_value": "کلینیک نامعتبر می\u200cباشد",
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="Clinic.clinics",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True, related_name="doctors", to="Clinic.doctorservices"
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "db_table": "Doctors",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "status"], name="Doctors_clinic__d1140c_idx"
                    )
                ],
            },
        ),
    ]
