# Generated by Django 5.2.14 on 2026-05-10 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Clinic", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
