# Generated by Django 5.2.14 on 2026-05-10 03:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("schedule_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Cancelled", "کنسل شده"),
                            ("Closed", "به اتمام رسیده"),
                            ("Open", "جاری"),
                        ],
                        default="Open",
                        max_length=10,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "db_table": "Schedule",
                "ordering": ["-schedule_date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "schedule_date", "status"],
                        name="Schedule_doctor__2f8684_idx",
                    )
                ],
            },
        ),
    ]
