# Generated by Django 5.2.14 on 2026-05-10 03:49

import uuid

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insurances",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام بیمه")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Base", "بیمه پایه"),
                            ("Supplementary", "بیمه تکمیلی"),
                            ("Full", "بیمه فول درمان"),
                        ],
                        max_length=20,
                        verbose_name="نوع بیمه",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Disable", "غیرفعال"), ("Enable", "فعال")],
                        max_length=13,
                        verbose_name="وضعیت",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Insurance",
                "verbose_name_plural": "Insurances",
                "db_table": "insurances",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["type", "status"], name="insurances_type_0e536b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "type"), name="unique_insurance_name_type"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "text",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Biography"),
                ),
                (
                    "pic",
                    models.ImageField(
                        default="news/news_def.png",
                        error_messages={
                            "blank": "لطفاً یک عکس انتخاب کنید.",
                            "empty": "فایل بارگذاری شده خالی است.",
                            "invalid": "فایل انتخاب شده معتبر نیست.",
                            "invalid_image": "فایل ارسالی خراب می\u200cباشد",
                            "missing": "هیچ فایلی برای بارگذاری انتخاب نشده است.",
                        },
                        upload_to="news/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"],
                                message="فقط فایل\u200cهای تصویری با فرمت JPG, JPEG, PNG مجاز هستند.",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Disable", "غیرفعال"), ("Enable", "فعال")],
                        default="Enable",
                        max_length=15,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "db_table": "News",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["created_date"], name="News_created_95b545_idx"
                    )
                ],
            },
        ),
    ]
