# Generated by Django 5.2.14 on 2026-05-10 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Account", "0001_initial"),
        ("Schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("chat", "مشاوره متنی"),
                            ("online_reservation", "رزرو نوبت آنلاین"),
                            ("oncall_reservation", "رزرو نوبت تلفنی"),
                        ],
                        default="online_reservation",
                        max_length=25,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cancelled", "کنسل شده"),
                            ("pending", "در انتظار پاسخ"),
                            ("answered", "پاسخ داده شد"),
                        ],
                        default="pending",
                        max_length=18,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "reception",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="received_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="Schedule.schedule",
                    ),
                ),
                (
                    "sub_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="Account.subuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "db_table": "Reservation",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="Reservation_user_id_9ce715_idx"
                    ),
                    models.Index(
                        fields=["schedule", "status"],
                        name="Reservation_schedul_12d6bc_idx",
                    ),
                    models.Index(
                        fields=["reception"], name="Reservation_recepti_49c8be_idx"
                    ),
                ],
            },
        ),
    ]
